### ISSUE TITLE
Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by DanishAjaib** [hadiidbouk/ChartProgressBar-Android#14]
Getting this error:
`Process: com.spesa.app, PID: 12699
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:259)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:920)
        at android.content.res.Resources.getDrawable(Resources.java:860)
        at android.content.res.Resources.getDrawable(Resources.java:835)
        at com.hadiidbouk.charts.ChartProgressBar.build(ChartProgressBar.java:131)`

at line:

`mChart.build()`

I have added ic_pin.xml in the drawables folder

**Comment by Manoucha** [comment]
i have the same problem , even after i added ic_pin.xml

**Comment by DanishAjaib** [comment]
This library is not maintained anymore. I don't think we'll get any help.

**Comment by Manoucha** [comment]
oh ! do you know any other library similar to this one?

**Comment by DanishAjaib** [comment]
https://github.com/PhilJay/MPAndroidChart   .. This one is pretty good.

**Comment by omkar-tenkale** [comment]
I solved it by adding:

                    app:hdPinDrawable="@drawable/ic_pin"


Code for drawable/ic_pin.xml 
https://github.com/hadiidbouk/ChartProgressBar-Android/blob/master/sample/src/main/res/drawable/ic_pin.xml

![image](https://user-images.githubusercontent.com/39808155/148836895-4f19a1f8-26a3-4737-abf0-76e0a3d8d67c.png)
![image](https://user-images.githubusercontent.com/39808155/148836948-4c57353d-4fac-4af4-8443-d68988432e00.png)
